### ISSUE TITLE
desc48_get_provider vs desc48_get_service ...

### ISSUE THREAD

**Issue by debugasm** [gfto/bitstream#1]
Hi,

in the descriptr 0x48 the returned parameter is different, one is "const" one is not.

```
static inline const uint8_t *desc48_get_provider(const uint8_t *p_desc,
                                                 uint8_t *pi_length)
{
    const uint8_t *p = p_desc + DESC48_HEADER_SIZE;
    *pi_length = p[0];
    return p + 1;
}

static inline uint8_t *desc48_get_service(const uint8_t *p_desc,
                                          uint8_t *pi_length)
{
    uint8_t *p = (uint8_t *)p_desc + DESC48_HEADER_SIZE + 1 + p_desc[3];
    *pi_length = p[0];
    return p + 1;
}
```
The first one generate "warning", in my opinion, the structure of "desc48_get_service" is more correct and can also be used for "desc48_get_provider"

```
static inline uint8_t *desc48_get_provider(const uint8_t *p_desc,
                                           uint8_t *pi_length)
{
    uint8_t *p = (uint8_t *)p_desc + DESC48_HEADER_SIZE;
    *pi_length = p[0];
    return p + 1;
}
```

debugasm

**Comment by gfto** [comment]
Can you please submit a patch to fix the issue ?

**Comment by debugasm** [comment]
Hi,

I'm not very familiar with the "patches" I'm sorry. I add the code, however, in my opinion more correct, for "desc48_get_provider":
```
static inline uint8_t *desc48_get_provider(const uint8_t *p_desc,
                                           uint8_t *pi_length)
{
    const uint8_t *p = (uint8_t *)p_desc + DESC48_HEADER_SIZE;
    *pi_length = p[0];
    return p + 1;
}
```

**Comment by gfto** [comment]
Here are how functions look in master branch. They seem correct to me. The _set_ functions are not taking const and _get_ functions are (this pattern is used all over bitstream):

  static inline void desc48_set_provider(uint8_t *p_desc,
                                       const uint8_t *p_provider,
                                       uint8_t i_length)
  static inline void desc48_set_service(uint8_t *p_desc,
                                      const uint8_t *p_service,
                                      uint8_t i_length)

  static inline const uint8_t *desc48_get_provider(const uint8_t *p_desc,
                                                 uint8_t *pi_length)
  static inline uint8_t *desc48_get_service(const uint8_t *p_desc,
                                          uint8_t *pi_length)

What am I missing?

**Comment by debugasm** [comment]
Why "desc48_get_provider" return "**const** uint8_t *" and "desc48_get_service" return "uint8_t *" ?

**Comment by gfto** [comment]
Thanks, now I see it. You are correct, it should return const.

**Comment by debugasm** [comment]
Well, even my eyes sometimes hide things from me.

**Comment by gfto** [comment]
I've submitted fix to upstream repo.
